noahdesu/zlog

- README.md
> doc: update cls_zlog tutorial

- .gitignore
- .travis.yml
- README.md
- configure.ac
- m4/ax_cxx_compile_stdcxx_11.m4
- src/Makefile.am
- src/libseqr.h
- src/libzlog.cc
- src/libzlog.h
- src/zlog-bench-ng.cc
> add asynchronous interfaces

- docker/ci/Dockerfile
- docker/ci/README.md
- docker/ci/entrypoint.sh
- docker/ci/micro-osd.sh
> docker: add ci image

- .travis.yml
- README.md
- docker/ci/Dockerfile
- docker/ci/entrypoint.sh
> ci: use docker zlog/ci image in travis

- docker/ci/entrypoint.sh
> ci: support volume and custom branch

- docker/ci/README.md
> ci: update ci docker readme

- .travis.yml
- docker/ci/entrypoint.sh
> ci: pass travis clone dir to docker

- docker/ci/run.sh
- src/java/Makefile.am
- src/java/src/test/java/com/cruzdb/AllTests.java
- src/java/src/test/java/com/cruzdb/LogTest.java
> java: add junit-based tests

- src/bench/plot_latency.py
> bench: plot throughput and trace combinations

- docker/physical-design/jewel-bluestore.conf
- docker/physical-design/runner.sh
- docker/physical-design/single-node-ceph.sh
Signed-off-by: Michael Sevilla <mikesevilla3@gmail.com>
> bench: add some bluestore goodness

- src/CMakeLists.txt
- src/kvstore/CMakeLists.txt
- src/kvstore/backend.h
- src/kvstore/db.cc
- src/kvstore/db.h
- src/kvstore/db_test.cc
- src/kvstore/node_cache.cc
- src/kvstore/rbt.cc
- src/kvstore/thrash.cc
- src/kvstore/transaction.cc
> kvstore: add vector and zlog backend

- src/include/zlog/db.h
- src/include/zlog/iterator.h
- src/include/zlog/transaction.h
- src/kvstore/CMakeLists.txt
- src/kvstore/db_impl.cc
- src/kvstore/db_impl.h
- src/kvstore/db_test.cc
- src/kvstore/iterator_impl.cc
- src/kvstore/iterator_impl.h
- src/kvstore/iterator_test.cc
- src/kvstore/node_cache.cc
- src/kvstore/node_cache.h
- src/kvstore/rbt.cc
- src/kvstore/thrash.cc
- src/kvstore/transaction_impl.cc
- src/kvstore/transaction_impl.h
> kvstore: separate impl from db interface

- ci/after_success.sh
- ci/script.sh
> ci: coverage should use in-tree build

- .travis.yml
- ci/before_install.sh
- ci/script.sh
> ci: enable coverity for new travis-ci config

- src/include/zlog/transaction.h
- src/kvstore/transaction_impl.cc
- src/kvstore/transaction_impl.h
- src/test/db_test.cc
Hopefully the first of many to come.
I'm still diving into the codebase whenever I have the time, so I wouldn't be surprised if something in the code was off.
Thanks to Noah for helping me getting started.
Signed-off-by: Rubén Rincón <rubrinbla@gmail.com>
> Adresses #98, introducing a Get() method

- src/include/zlog/backend/ceph.h
- src/libzlog/backend/ceph.cc
This PR closes #74 
All test passed so I guess I didn't mess up anything.
What branch should I push PRs to?
Signed-off-by: Rubén Rincón <rubrinbla@gmail.com>
> Moved backend/ceph.h implementations to backend/ceph.cc

- ci/script.sh
> ci: fix osx build

- doc/storage/index.rst
> doc: add jewel notes

- doc/api/index.rst
- doc/build.sh
- src/java/CMakeLists.txt
> doc: add javadocs to generated site

- .travis.yml
- install-deps.sh
- src/libzlog/aio.cc
- src/libzlog/backend.cc
- src/libzlog/capi.cc
> zlog: managed-seqclient bug fixes
